#Build a pupeline

name: webstore-pipe
on: 
    workflow_dispatch: 

jobs:
    build_1:
        name: "Build in Publish from github"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: restore
              run: dotnet restore
# creata and starte the vm.
            - run: dotnet build --configuration Release
              name: building

            - run: dotnet publish --configuration Release -o ./webstore

# Added a artifact
            - name: upload buuld artifact
              uses: actions/upload-artifact@v4.5.0
              with:
                  name: webstore
                  path: ./webstore
